### ISSUE TITLE
Test shooter code to find good speeds at set distances and then adjust the angle to score

### ISSUE THREAD

**Issue by MasonDiGi** [Team41Robotics/2022-Robot-Code#28]
Put all data in spreadsheet (angle, speed, and distance)

**Comment by waffleattack** [comment]
[SPREADSHEET OF DATA](https://docs.google.com/spreadsheets/d/1BFzn8sWV79qqFcdtHm0MZqVvdoMpmBPzStduzsE3gaI/edit?usp=sharing)
